version: "3.8"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces/cauliflow:cached
      - venv:/workspaces/cauliflow/.venv
    command: sleep infinity

  ioc:
    image: ghcr.io/epics-containers/epics-base-developer:7.0.8ad3
    stdin_open: true
    tty: true

volumes:
  venv:
